### ISSUE TITLE
Load BioBERT weights

### ISSUE THREAD

**Issue by JohnGiorgi** [BaderLab/saber#135]
Figure out how to load BioBERTs weights.

See these links for help.

- https://github.com/MeRajat/SolvingAlmostAnythingWithBert/tree/master/biobert_ner
- https://github.com/dmis-lab/biobert/issues/2

**Comment by JohnGiorgi** [comment]
Documenting how I finally got this to work:

1. Download one of the BioBERT pre-trained models from [here](https://github.com/naver/biobert-pretrained/releases).
2. Clone and `cd` into `pytorch-pretrained-BERT`: 

```
git clone https://github.com/huggingface/pytorch-pretrained-BERT.git 
cd pytorch-pretrained-BERT
```

3. Open `pytorch-pretrained-BERT/pytorch-pretrained-BERT/modeling.py`. Under the line `init_vars = tf.train.list_variables(tf_path)` add these two lines: 

```
excluded = ['BERTAdam','_power','global_step']
init_vars = list(filter(lambda x:all([True if e not in x[0] else False for e in excluded]),init_vars))
```

4. From the top-level of the `pytorch-pretrained-BERT` repo, call:

```
$BERT_BASE_DIR=../biobert_v1.1_pubmed
pytorch_pretrained_bert convert_tf_checkpoint_to_pytorch \                                                                                                                                              
  $BERT_BASE_DIR/model.ckpt-1000000 \                    
  $BERT_BASE_DIR/bert_config.json \
  $BERT_BASE_DIR/pytorch_model.bin
```

Where `BERT_BASE_DIR` should point to the downloaded and uncompressed [BioBERT model](https://github.com/naver/biobert-pretrained/releases) and `model.ckpt-1000000` should be whatever the checkpoint is named for that particular model.

5. Finally, place `pytorch_model.bin`, `bert_config.json` and `vocab.txt` (from `BERT_BASE_DIR`) in a folder `biobert` and `tar.gz` compress it with

```
tar -cvzf biobert.tar.gz biobert
```

This model can then be loaded with

```
model = BertForTokenClassification.from_pretrained('path/to/biobert.tar.gz', num_labels=num_labels)
self.tokenizer = BertTokenizer.from_pretrained('path/to/biobert.tar.gz', do_lower_case=False)
```

**Comment by jhyuklee** [comment]
Hi, we've updated all the other BioBERT weights (v1.0) as the same format as v1.1, so it should work now.
Thank you.

**Comment by JohnGiorgi** [comment]
That’s great, thanks for letting me know. Is there any reason to use v1.0 if I just want the best performance possible? Or should I stick with v1.1?

**Comment by jhyuklee** [comment]
For most tasks, it will be better to stick with with v1.1, but v1.0 (+PubMed 200K +PMC 270K) works well, too  as shown in the paper (only minor differences). Note that we haven't updated our paper with performance of v1.1 (will take some time).
If performance on a single targeted task matters, you can compare them and choose what to use.

**Comment by JohnGiorgi** [comment]
Right. Okay great, thanks for the response!

**Comment by Colelyman** [comment]
Thanks for sharing what worked for you. I followed the steps provided and everything worked except I discovered (as of writing) that when compressing the files together they can't be in a directory, they just have to be flat.

**Comment by phaniram-sayapaneni** [comment]
> Hi, we've updated all the other BioBERT weights (v1.0) as the same format as v1.1, so it should work now.
> Thank you.

Hi @jhyuklee , the download files[BioBERT-Base v1.1 (+ PubMed 1M] donot contain .ckpt file, it has : model.ckpt-1000000.data-00000-of-00001, model.ckpt-1000000.index, model.ckpt-1000000.meta

which one is an accurate checkpoint file?
when I try load weights from model.ckpt-1000000.data-00000-of-00001 --> tf.train.list_variables('model.ckpt-1000000.data-00000-of-00001') it is throwing me error:

DataLossError: Unable to open table file biobert_v1.1_pubmed/model.ckpt-1000000.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?


need to port the bio-bert to pytorch, to be able to compare with other SOTA/research models

**Comment by phaniram-sayapaneni** [comment]
Hi @JohnGiorgi , I tried the steps you mentioned, but this error while importing the gz file:
`UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte`

any hints?

**Comment by JohnGiorgi** [comment]
Hi @phaniram-sayapaneni,

Are you simply looking to load BioBERT with HF Transformers? If so, you can follow this code: https://huggingface.co/monologg/biobert_v1.1_pubmed.

If you search BioBERT [here](https://huggingface.co/models) you can see several varients and how to load them.
