### ISSUE TITLE
Cannot install saber (broken library dependencies)

### ISSUE THREAD

**Issue by AlbinaGalimzyanova** [BaderLab/saber#185]
_**1. Installing saber in new conda virtual environment:**_

`pip install git+https://github.com/BaderLab/saber.git`

ERROR: thinc 6.10.3 has requirement **wrapt<1.11.0,>=1.10.0**, but you'll have wrapt 1.11.2
which is incompatible.
ERROR: multiprocess 0.70.9 has requirement dill>=0.3.1, but you'll have dill 0.2.9 which is
incompatible.
ERROR: fastai 1.0.58 has requirement spacy>=2.0.18, but you'll have spacy 2.0.13 which is
incompatible.
ERROR: en-core-web-sm 2.1.0 has requirement spacy>=2.1.0, but you'll have spacy 2.0.13
which is incompatible.

_**2. Trying to fix dependency errors:**_

`pip install wrapt==1.10.0`

ERROR: tensorflow 1.15.0rc3 has requirement **wrapt>=1.11.1**, but you'll have wrapt 1.10.0
which is incompatible.
ERROR: fastai 1.0.58 has requirement spacy>=2.0.18, but you'll have spacy 2.0.13 which is
incompatible.
ERROR: en-core-web-sm 2.1.0 has requirement spacy>=2.1.0, but you'll have spacy 2.0.13
which is incompatible.

_Also doesn't fix the problem:_
`pip install git+https://www.github.com/keras-team/keras-contrib.git`
`pip install
https://github.com/huggingface/neuralcoref-models/releases/download/en_coref_md-3.0.0/e
n_coref_md-3.0.0.tar.gz`

_**3. If I try to use saber anyway, this error is always displayed:**_

TypeError: Tensors in list passed to 'values' of 'ConcatV2' Op have types [bool, float32] that
don't all match.

_I tried to install saber on colab, Windows and Ubuntu_

**Comment by JohnGiorgi** [comment]
Hi @AlbinaGalimzyanova,

Thank you for pointing this out! 

I found that the issue was with the Keras dependency. Pinning it to `keras==2.2.4` fixed the issue.  Although I still get the warnings you mentioned, I tested that [the colab](https://colab.research.google.com/drive/1WD7oruVuTo6p_908MQWXRBdLF3Vw2MPo) now runs without error.

If you are still having issues, please let me know.

**Comment by albinafisher** [comment]
@JohnGiorgi Thanks for the quick reply, now everything works :)
