### ISSUE TITLE
Cannot evaluate model with a suggested workaround

### ISSUE THREAD

**Issue by albinafisher** [BaderLab/Saber#187]
Hello, I have a problem with evaluating the model. I tried the code from the issue https://github.com/BaderLab/saber/issues/125.

```
from saber.saber import Saber
from saber.metrics import Metrics
from saber import constants

constants.UNK = '<UNK>'
constants.PAD = '<PAD>'

sb = Saber()
sb.load('/home/pretrained_models/pretrained_model_A')
sb.load_dataset('/home/datasets/dataset_B')

sb.config.criteria = 'right'

evaluation_data = sb.model.prepare_data_for_training()[0]

print(sb.datasets[-1].idx_to_tag)

metric = Metrics(sb.config, sb.model, evaluation_data, sb.datasets[-1].idx_to_tag, './', model_idx=0)

test_scores = metric._evaluate(evaluation_data['x_test'], evaluation_data['y_test'])
metric.print_performance_scores(test_scores, title='test')
```

I fixed a few minor problems by myself (extra argument sb.model in the Metrics initialization and dataset partition in the _evaluate method). But there is a problem:

AttributeError                            Traceback (most recent call last)
<ipython-input-8-ec0f56dafa79> in <module>()
     14 metric = Metrics(sb.config, evaluation_data, sb.datasets[-1].idx_to_tag, './', model_idx=0)
     15 
---> 16 test_scores = metric._evaluate(evaluation_data['x_test'], evaluation_data['y_test'])
     17 metric.print_performance_scores(test_scores, title='test')

1 frames
/usr/local/lib/python3.6/dist-packages/saber/metrics.py in _get_y_true_and_pred(self, X, y)
    111         y_true = np.asarray(y_true).ravel() # flatten to 1D array
    112         # predicted labels
--> 113         y_pred = self.model.predict(X, batch_size=constants.PRED_BATCH_SIZE)
    114         y_pred = np.asarray(y_pred.argmax(axis=-1)).ravel()
    115 

AttributeError: 'Metrics' object has no attribute 'model'

Could you help me with this problem, please?

**Comment by JohnGiorgi** [comment]
Which branch are you working off of, master?

**Comment by albinafisher** [comment]
Yes, I have cloned the master branch

**Comment by albinafisher** [comment]
I found that in the development branch there is more suitable code, but also face a problem. For example, I cannot load pretrained model, an error appears:

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-5-9fe886c6f9b1> in <module>()
----> 1 sb.load('/content/BioNLP11ID_PRGE_BIO')

/usr/local/lib/python3.6/dist-packages/saber/saber.py in load(self, directory)
    252                     config=self.config,
    253                     datasets=datasets,
--> 254                     pretrained_model_name_or_path=model_attributes['pretrained_model_name_or_path']
    255                 )
    256                 model.load(model_dir)

KeyError: 'pretrained_model_name_or_path'

**Comment by albinafisher** [comment]
Should I roll back to some special commit?

**Comment by JohnGiorgi** [comment]
Hey @AlbinaGalimzyanova,

Saber is no longer being maintained. If you need it to reproduce a score from our paper let me know and I can dig into this problem (or just report the score directly). Otherwise, I would look elsewhere for IE tools for biomed (like [Stanzy](https://stanfordnlp.github.io/stanza/biomed.html)). Thanks!
