### ISSUE TITLE
Expose pretrained model performance and evaluation datasets

### ISSUE THREAD

**Issue by swartchris8** [BaderLab/Saber#189]
To decide whether to use this library it would be good to see NER and entity linking level metrics for the different pretrained models. 

From the google colab the section describing pretrained models wasn't helpful it sent me here: https://baderlab.github.io/saber-api-docs/#introduction where it was good that the entity linking namespace was exposed but performance for NER and entity linking were missing.

For my use case exposing model performance and making this visible would be very useful.

**Comment by JohnGiorgi** [comment]
You are right, this would definitely be useful.

Unfortunately (and at least for the time being, this could change) I am no longer working on the library. I realized that better solutions exist for my use cases ([AllenNLP](https://allennlp.org/) or [SpaCy](https://spacy.io/) being examples).
