### ISSUE TITLE
Error with sb.load('PRGE')

### ISSUE THREAD

**Issue by sammiyo** [BaderLab/Saber#198]
On loading the PRGE model, I am facing issues. 'module 'tensorflow' has no attribute 'placeholder' . On downgrading the tf version, new errors are coming up. I followed the google colab notebook but its not working. Please help!

**Comment by JohnGiorgi** [comment]
Hi @sammiyo,

We are no longer maintaining this code. Please let me know if you need to evaluate the model for a paper comparison and I will try to help you out.
