### ISSUE TITLE
error with python enviornment setup process

### ISSUE THREAD

**Issue by jswu18** [BaderLab/saber#87]
Trying to setup python environment with anaconda and following the instructions outlined on the repository:

Error 1: installing saber with "pip install ." inside the saber folder
<img width="1440" alt="pip install" src="https://user-images.githubusercontent.com/23536446/48103020-a1a84300-e1fb-11e8-879c-a4122803b1b3.png">

Error 2: installing en_coref_md, tried running twice but the same errors come up
<img width="1440" alt="en_coref_md" src="https://user-images.githubusercontent.com/23536446/48103170-06fc3400-e1fc-11e8-813b-99d607f5e2d9.png">
<img width="1440" alt="spacy" src="https://user-images.githubusercontent.com/23536446/48103172-06fc3400-e1fc-11e8-86c8-a79d1b61d873.png">

**Comment by JohnGiorgi** [comment]
Weird, looks like issues are related to `gcc`. I suspect this is an issue with your Command Line Tools.

**First**, try this (as per [this](https://stackoverflow.com/a/44851671/6578628) SO post):

```
# activate your environment
source activate saber
# install gcc compiler into this environment
conda install gcc
# reinstall saber
git clone https://github.com/BaderLab/saber.git
cd saber
pip install .
pip install git+https://www.github.com/keras-team/keras-contrib.git
pip install https://github.com/huggingface/neuralcoref-models/releases/download/en_coref_md-3.0.0/en_coref_md-3.0.0.tar.gz
```

**If that doesn't work**, try reinstalling the Xcode Command Line Tools. [Here](https://apple.stackexchange.com/a/324598) are some good instructions, but they require that you have `brew` installed (which is a good idea anyway). After updating the CLTs, re-install saber as per above.

Let me know if either solution fixes the problem!

**Comment by jswu18** [comment]
Turns out I had to update my OS…I have everything working again
