### ISSUE TITLE
Grounding sometimes hangs

### ISSUE THREAD

**Issue by JohnGiorgi** [BaderLab/saber#90]
Sometimes, when `Saber.annotate()` is called, the annotation process hangs during the grounding step.

It might be better to put a maximum wait time on the grounding step so that it is cancelled or an error is reported to the user if this wait time is passed.

**Comment by IgorRodchenkov** [comment]
@JohnGiorgi how it's better to reproduce? 
I also suspect that we should  always specify organisms (names or taxids) and perhaps limit,
e.g., grounding_utils.ground(annotation, ('human', 'mouse'), limit=20);
otherwise it matches too many entries and takes time...

**Comment by JohnGiorgi** [comment]
Closing this as grounding is now done by [EXTRACT 2.0 API](https://extract.jensenlab.org/).
